### ISSUE TITLE
take descr from source archive

### ISSUE THREAD

**Issue by whitequark** [OCamlPro/opam-publish#12]
Currently, as I understand it, opam-publish will take opam from the newly downloaded source archive, but descr is taken from the repository. I think if descr exists in the source archive, it also should be taken from there.

**Comment by AltGr** [comment]
it should, if you have a _directory_ `opam` containing `opam` and `descr` files at the root of your package source.

**Comment by whitequark** [comment]
Well, I don't. I just have the file `opam`. It should take the `opam` file as well, at least, since this is valid for pinning.

**Comment by whitequark** [comment]
I fixed my build recipe instead to do a `cp`.
