### ISSUE TITLE
Can't seem to publish, getting permissions 

### ISSUE THREAD

**Issue by fxfactorial** [OCamlPro/opam-publish#22]
I keep getting these permissions errors trying to publish to opam, 

opam-publish submit ./lambda-invaders.1.0
[v1.1.tar.gz] Downloading https://github.com/fxfactorial/lambda-invaders/archive/v1.1.tar.gz
Please enter your github name: fxfactorial
 opam-version 1.2.0
 os           darwin
 command      git clone git@github.com:ocaml/opam-repository.git /Users/Edgar/.opam/plugins/opam-publish/repos/default
 path         /Users/Edgar/Repos/lambda-invaders
 exit-code    128
 env-file     /var/folders/31/fdpzgydn611cp5mly2p9hv3c0000gn/T/opam-974/log/log-974-5f1023.env
 stdout-file  /var/folders/31/fdpzgydn611cp5mly2p9hv3c0000gn/T/opam-974/log/log-974-5f1023.out
 stderr-file  /var/folders/31/fdpzgydn611cp5mly2p9hv3c0000gn/T/opam-974/log/log-974-5f1023.err
stderr ###
 Cloning into '/Users/Edgar/.opam/plugins/opam-publish/repos/default'...
 Permission denied (publickey).
 fatal: Could not read from remote repository.
 
 Please make sure you have the correct access rights
 and the repository exists.

running wget on the url is totally fine, so I'm not sure what's the issue.

**Comment by samoht** [comment]
```
git clone git@github.com:ocaml/opam-repository.git 
```
you are not supposed to clone the `git@` repo but the `https://...git` one. Not sure how you managed to get that.

**Comment by fxfactorial** [comment]
I don't know either, FWIW the http field in the url file says

http: "https://github.com/fxfactorial/lambda-invaders/archive/v1.1.tar.gz"

Could something be wrong in the opam file? my opam-publish version is 0.2.1

**Comment by AltGr** [comment]
@samoht: no, opam-publish clones using ssh since we later submit pull-requests. This indeed requires that you have a ssh key registered in github -- guess that was already in the setup of everyone who tested, @fxfactorial would it explain the issue ?

In any case, we should _at least_ document it.

**Comment by fxfactorial** [comment]
@AltGr That's totally what it was, I guess I never had to have my keys with github cause I used some kind of git sox-keychain helper.
