### ISSUE TITLE
Mandatory long description

### ISSUE THREAD

**Issue by Drup** [OCamlPro/opam-publish#25]
```
[ERROR] In /home/gabriel/source/llvmgraph/llvmgraph.0.2/descr:
  - long description unspecified
```

Sometimes, packages just don't need a long description. :)
(and this is not enforced by opam lint)

**Comment by dbuenzli** [comment]
If you need to publish I guess you can work around with a U+00A0.

**Comment by AltGr** [comment]
Ah, this is fixed already on master, we should probably ship a new release!
