### ISSUE TITLE
Spurious whitespace chars after the version number

### ISSUE THREAD

**Issue by alainfrisch** [OCamlPro/opam-publish#37]
I tried to use opam-publish for the first time today, doing:

````
opam-publish prepare https://github.com/LexiFi/gen_js_api/archive/v1.0.tar.gz
````

It created a directory `gen_js_api.1.0   /` (with 3 whitespace chars after the '0'), which I had to rename manually.  How does the tool infer the package name and version number?

**Comment by AltGr** [comment]
It doesn't infer: that's how it's specified in `https://github.com/LexiFi/gen_js_api/blob/master/opam`...
