### ISSUE TITLE
add the list of changes to the PR

### ISSUE THREAD

**Issue by samoht** [OCamlPro/opam-publish#8]
This is kind of a complex feature request, but that would be great if we could have the list of changes displayed in the description of the PR. A possible idea on how to do that:

- look at the root of the archive for `CHANGES`, `CHANGES.txt` or `CHANGES.md`
- diff the file with the previous released version
- add the new entries in the PR description

**Comment by dbuenzli** [comment]
> This is kind of a complex feature request, but that would be great if we could have the list of changes displayed in the description of the PR.

In fact there's a very simple solution to this that `topkg`'s release tools could support readily. The idea is that a `$PACKAGE.$VERSION/msg` file in the package directory is picked up by `opam-publish submit` and simply appended to the PR message after the `descr`. The path is however ignored for the commit (i.e. not commited to the repo).

For people using the `opam-publish prepare` step this should materialize trough a `--msg` option that simply writes it to the path mentioned above.

**Comment by dbuenzli** [comment]
Note that simply having a `--msg` option to `opam-publish submit` with the release notes to be appended to PR message would also do (rather than muddy the package directory with things to ignore).

**Comment by dsheets** [comment]
You may also be interested in https://github.com/dsheets/ocaml-changes which is able to parse the de facto Mirage `CHANGES` format idempotently. It can handle `cohttp`'s change log with minimal manual fix-ups. Right now, it's almost-but-not-quite markdown and it wouldn't be very hard to use it to convert all of the Mirage-like changelogs to markdown. It could then be plugged into this `--msg` flag to dump a release's changelog into the publication PR.

**Comment by dbuenzli** [comment]
In fact `topkg` already has a change log extraction [function](http://erratique.ch/software/topkg/doc/Topkg_care.Text.html#VALchange_log_last_entry) that supports markdown and asciidoc, see the details [here](https://github.com/dbuenzli/topkg/blob/master/src-bin/log.ml#L81-L109). This is used to give the release notes to the publication delegate (e.g. to publish on gh `releases`) and will be used with `topkg opam submit` once this is in.
